import anthropic
import requests
import streamlit as st

STOCKS = {
    "Apple (AAPL)": "AAPL",
    "Microsoft (MSFT)": "MSFT",
    "Amazon (AMZN)": "AMZN",
    "NVIDIA (NVDA)": "NVDA",
    "Tesla (TSLA)": "TSLA",
    "Google (GOOGL)": "GOOGL",
}

ANTHROPIC_API_KEY = st.secrets.get("ANTHROPIC_API_KEY")


def fetch_quote(symbol):
    try:
        token = st.secrets.get("FINNHUB_API_KEY")
        if not token:
            return None, "Finnhub API key missing."

        headers = {
            "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AI-Market-Dashboard/1.0"
        }

        res = requests.get(
            f"https://finnhub.io/api/v1/quote?symbol={symbol}&token={token}",
            headers=headers,
            timeout=10,
        )
        res.raise_for_status()
        data = res.json()
        if not data or data.get("c", 0) == 0:
            return None, f"No data found for {symbol}."
        return data, None
    except requests.exceptions.RequestException as e:
        return None, f"Network error fetching stock data: {str(e)}"
    except Exception as e:
        return None, f"Unexpected error: {str(e)}"


def get_ai_stock_comparison(stock1_data, stock2_data, language="English"):
    """Compare two stocks using Claude without providing financial advice."""
    if not ANTHROPIC_API_KEY:
        return None, "Claude API key was not found in secrets.toml."

    q1, s1 = stock1_data["quote"], stock1_data["symbol"]
    q2, s2 = stock2_data["quote"], stock2_data["symbol"]

    prompt = f"""
Compare the following two stock quotes in {language} based purely on today's trading data.

Stock 1 ({s1}):
- Current Price: ${q1.get('c', 0):.2f}
- Price Change: ${q1.get('d', 0):+.2f}
- Percentage Change: {q1.get('dp', 0):+.2f}%
- Open Price: ${q1.get('o', 0):.2f}
- Previous Close: ${q1.get('pc', 0):.2f}
- Day High: ${q1.get('h', 0):.2f}
- Day Low: ${q1.get('l', 0):.2f}

Stock 2 ({s2}):
- Current Price: ${q2.get('c', 0):.2f}
- Price Change: ${q2.get('d', 0):+.2f}
- Percentage Change: {q2.get('dp', 0):+.2f}%
- Open Price: ${q2.get('o', 0):.2f}
- Previous Close: ${q2.get('pc', 0):.2f}
- Day High: ${q2.get('h', 0):.2f}
- Day Low: ${q2.get('l', 0):.2f}

Use this structure:
1. Relative Momentum: Compare which stock showed stronger intraday performance today.
2. Key Metric Highlights: Direct comparison of percentage change and volatility (low to high spread).
3. Educational Takeaway: Explain what these comparative figures mean in plain language.

Use only the provided numbers. Do not predict future movements or recommend buying, selling, or holding either stock.
"""

    try:
        client = anthropic.Anthropic(api_key=ANTHROPIC_API_KEY)
        message = client.messages.create(
            model="claude-sonnet-5",
            max_tokens=800,
            system=(
                "You are a careful educational stock-data explainer. "
                "Be concise, factual, and easy to understand."
            ),
            messages=[{"role": "user", "content": prompt}],
        )

        explanation = "\n".join(
            block.text
            for block in message.content
            if getattr(block, "type", None) == "text"
        )

        if not explanation:
            return None, "Claude returned an empty response."

        return explanation, None

    except anthropic.AuthenticationError:
        return None, "Claude rejected the API key. Check ANTHROPIC_API_KEY."
    except anthropic.RateLimitError:
        return None, "Claude rate limit reached. Please try again later."
    except anthropic.APIConnectionError:
        return None, "Unable to connect to Claude right now."
    except anthropic.APIError as e:
        return None, f"Claude API Error: {e.message}"
    except Exception as e:
        return None, f"Unexpected error: {str(e)}"


def show():
    """Streamlit view function called by app.py."""
    st.markdown(
        '<div class="dash-title">⚔️ AI <span>Stock Comparison</span></div>',
        unsafe_allow_html=True,
    )
    st.markdown(
        '<div class="dash-caption">Side-by-side market data analysis generated by Claude.</div>',
        unsafe_allow_html=True,
    )

    if not ANTHROPIC_API_KEY:
        st.error("Claude API key missing in secrets.toml.")
        return

    col1, col2 = st.columns(2)

    with col1:
        stock1_label = st.selectbox(
            "Select First Stock",
            list(STOCKS.keys()),
            index=0,
            key="stock_1_select",
        )
    with col2:
        stock2_label = st.selectbox(
            "Select Second Stock",
            list(STOCKS.keys()),
            index=1,
            key="stock_2_select",
        )

    sym1 = STOCKS[stock1_label]
    sym2 = STOCKS[stock2_label]

    if sym1 == sym2:
        st.warning("Please select two different stocks to compare.")
        return

    if st.button("Compare Stocks with AI", type="primary", use_container_width=True):
        with st.spinner("Fetching stock data..."):
            q1, err1 = fetch_quote(sym1)
            q2, err2 = fetch_quote(sym2)

        if err1:
            st.error(f"Error loading {sym1}: {err1}")
            return
        if err2:
            st.error(f"Error loading {sym2}: {err2}")
            return

        # Display numeric metrics side-by-side
        c1, c2 = st.columns(2)
        with c1:
            st.metric(
                label=f"{sym1} Price",
                value=f"${q1['c']:.2f}",
                delta=f"{q1.get('dp', 0):+.2f}%",
            )
        with c2:
            st.metric(
                label=f"{sym2} Price",
                value=f"${q2['c']:.2f}",
                delta=f"{q2.get('dp', 0):+.2f}%",
            )

        # AI Comparison Analysis
        with st.spinner("Generating AI comparative analysis..."):
            stock1_data = {"symbol": sym1, "quote": q1}
            stock2_data = {"symbol": sym2, "quote": q2}
            analysis, ai_err = get_ai_stock_comparison(stock1_data, stock2_data)

            if ai_err:
                st.error(ai_err)
            else:
                with st.container(border=True):
                    st.markdown(analysis)